default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("SQLITE_DATABASE", "storage/development.sqlite3") %>

test:
  <<: *default
  database: <%= ENV.fetch("SQLITE_TEST_DATABASE", "storage/test.sqlite3") %>

production:
  <<: *default
  database: <%= ENV.fetch("SQLITE_DATABASE", "/data/production.sqlite3") %>
